url: http://production.frankfortccc.com
title: CCC Production

permalink: /manuals/:title.html

collections:
  manuals:
    output: true
defaults:
- scope:
    path: ""
    type: manuals
  values:
    layout: default

safe: true
lsi: false

exclude:
- CNAME
- Gemfile
- Gemfile.lock
- script
