#!/bin/bash
script/build
exec bundle exec ruby "$0" "$@"
#!ruby

require "html-proofer"

options = {
  :assume_extension => true,
  :allow_hash_href => true,
  :alt_ignore => [/./],
}
HTMLProofer.check_directory("./_site", options).run
